name: Push to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu_central_1
  ECR_REPOSITORY: pexon-danswer-internal

permissions:
  id-token: write
  contents: read  
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout actions-oidc-debugger
      uses: actions/checkout@v3
      with:
        repository: github/actions-oidc-debugger
        ref: main
        path: ./.github/actions/actions-oidc-debugger

    - name: Debug OIDC Claims
      uses: ./.github/actions/actions-oidc-debugger
      with:
        audience: 'sts.amazonaws.com'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
  
    - name: Docker Build and Push
      uses: docker/build-push-action@v5
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
      with:
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }}
          ${{ env.ECR_REPOSITORY_URI }}:latest

