name: Push to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: pexon-danswer-internal

permissions:
  id-token: write
  contents: read  
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        env:
          ECR_REGISTRY: my-registry
          ECR_REPOSITORY_URI: my-registry/my-repository
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.ref_type }}
          echo ${{ env.ECR_REPOSITORY_URI }}:${{ github.sha }}
          echo ${{ github.ref_name == 'main' ||  github.ref_type == 'tag' && format('{0}:latest', env.ECR_REPOSITORY_URI) || null}}
          echo ${{ github.ref_name != 'main' &&  github.ref_type != 'tag' && format('{0}:dev', env.ECR_REPOSITORY_URI) || format('{0}:main', env.ECR_REPOSITORY_URI)}}
